/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './*.html', './js/**/*.js'],
  safelist: [
    'bg-primary',
    'hover:bg-primary-dark',
    'text-white',
    'flex',
    'flex-col',
    'sm:flex-row',
    'flex-wrap',
    'gap-4',
    'justify-center',
    'justify-between',
    'inline-flex',
    'items-center',
    'gap-2',
    'rounded-xl',
    'rounded-2xl',
    'font-medium',
    'py-3',
    'px-6',
    'shadow-sm',
    'transition',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-3',
    'gap-5',
    'gap-6',
    'text-left',
    'items-start',
    'w-full',
    'max-w-3xl',
    'mx-auto',
    'mb-2',
    'mb-3',
    'mb-8',
    'mb-10',
    'mt-1',
    'fixed',
    'inset-0',
    'z-[100]',
    'hidden',
    'bg-black/50',
    'items-center',
    'justify-center',
    'p-4',
    'pointer-events-none',
    'pointer-events-auto',
    'shadow-xl',
    'max-w-md',
    'w-full',
    'max-h-[90vh]',
    'overflow-y-auto',
    'border-b',
    'border-slate-200',
    'text-lg',
    'font-semibold',
    'text-slate-800',
    'focus:ring-2',
    'focus:ring-primary',
    'focus:border-primary',
    'bg-emerald-50',
    'text-emerald-700',
    'bg-red-50',
    'text-red-700',
    'bg-amber-50',
    'text-amber-800',
    'bg-slate-100',
    'text-slate-700',
    'bg-emerald-100',
    'text-emerald-700',
    'bg-blue-100',
    'text-blue-700',
    'bg-amber-100',
    'text-amber-800',
    'backdrop-blur-sm',
    'shadow-2xl',
    'ring-2',
    'ring-slate-200/50',
    'border-l-4',
    'border-l-indigo-500',
    'text-xs',
    'text-slate-500',
    'border-slate-200/80',
    'lg:p-10',
    'sm:p-8',
    'p-6',
    'pt-24',
    'bg-primary/10',
    'hover:bg-primary/10',
    'hover:ring-primary/25',
    'max-w-6xl',
    'max-w-4xl',
    'sm:col-span-2',
    'lg:col-span-1',
    'hover:text-primary-dark',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#4f46e5',
        'primary-dark': '#4338ca',
        accent: '#7c3aed',
        surface: '#f8fafc',
      },
    },
  },
  plugins: [],
};
