/**
 * Home view – landing grid (hash routes). Styled for static GitHub Pages shell.
 */
var homeView = {
  route: 'home',
  navLabel: 'HOME Page',

  render: function () {
    return ''
      + '<div class="max-w-3xl mx-auto mb-10 text-center">'
      + '  <p class="mt-page-eyebrow">Operations toolkit</p>'
      + '  <h1 class="mt-page-title mb-3">Monitor Tools</h1>'
      + '</div>'
      + '<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">'
      + '  <a href="#/nested" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-sitemap"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Query Builder</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Build and compile monitor queries with field assist.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/checklist" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-clipboard-check"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Shift checklist</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Track shift tasks, handover notes, and history.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/shift-history" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-clock-rotate-left"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Shift history</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Unlock saved shifts with your history password.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/email" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-envelope"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Email generator</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Format and preview operational emails.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/tokens" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-key"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Tokens extractor</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Parse and extract token-like strings from text.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/analyze" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-chart-line"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Analyze logs</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Explore log timelines and search highlights.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/statistics" class="mt-tool-card text-left items-start">'
      + '    <span class="mt-tool-card-icon"><i class="fas fa-chart-bar"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">Slack alert stats</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Charts and breakdowns from Slack exports.</p>'
      + '    </div>'
      + '  </a>'
      + '  <a href="#/statistics-hubspot" class="mt-tool-card text-left items-start sm:col-span-2 lg:col-span-1">'
      + '    <span class="mt-tool-card-icon"><i class="fab fa-hubspot"></i></span>'
      + '    <div class="w-full">'
      + '      <p class="mt-tool-card-title text-left w-full">HubSpot statistics</p>'
      + '      <p class="text-xs text-slate-500 mt-1 leading-relaxed">Ticket volume, owners, and shift-style views.</p>'
      + '    </div>'
      + '  </a>'
      + '</div>';
  },

  mount: function () {}
};
(function () { window.MonitorToolsViews = window.MonitorToolsViews || {}; window.MonitorToolsViews.homeView = homeView; })();
